trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'bert-bot'

steps:
- task: Docker@2
  displayName: Build bert image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile